package com.deylauncher.server;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

public class ServerPropertiesManager {

    private final Path file;

    public ServerPropertiesManager(Path serverDir) {
        this.file = serverDir.resolve("server.properties");
    }

    /** Preserves insertion order and comment-free key=value lines -- good enough for a GUI editor round-trip. */
    public Map<String, String> read() {
        Map<String, String> map = new LinkedHashMap<>();
        if (!Files.exists(file)) return map;
        try {
            for (String line : Files.readAllLines(file)) {
                String trimmed = line.trim();
                if (trimmed.isEmpty() || trimmed.startsWith("#")) continue;
                int eq = trimmed.indexOf('=');
                if (eq < 0) continue;
                map.put(trimmed.substring(0, eq), trimmed.substring(eq + 1));
            }
        } catch (IOException ignored) {
        }
        return map;
    }

    public void write(Map<String, String> properties) throws IOException {
        Files.createDirectories(file.getParent());
        StringBuilder sb = new StringBuilder("#Generated by DeyLauncher\n");
        for (var e : properties.entrySet()) {
            sb.append(e.getKey()).append('=').append(e.getValue()).append('\n');
        }
        Files.writeString(file, sb.toString());
    }

    /** The handful of properties surfaced with dedicated controls rather than a raw key list -- everything else still round-trips untouched. */
    public static final String[] COMMON_KEYS = {
            "motd", "max-players", "difficulty", "gamemode", "pvp", "online-mode",
            "white-list", "allow-flight", "spawn-protection", "view-distance"
    };
}
