package com.deylauncher.server;

import com.deylauncher.modloader.NeoForgeInstaller;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

public class ServerProcessManager {

    private Process process;
    private OutputStream stdin;
    private final java.util.Set<String> onlinePlayers = java.util.Collections.synchronizedSet(new java.util.LinkedHashSet<>());
    private static final java.util.regex.Pattern JOINED_PATTERN =
            java.util.regex.Pattern.compile(":\\s*([A-Za-z0-9_]{1,16}) joined the game");
    private static final java.util.regex.Pattern LEFT_PATTERN =
            java.util.regex.Pattern.compile(":\\s*([A-Za-z0-9_]{1,16}) left the game");
    // The vanilla `list` command replies with either:
    //   "There are 3 of a max of 8 players online: Alice, Bob, Carol"  or
    //   "There are 0 of a max of 8 players online:"
    // This is the SERVER's authoritative answer, so parsing it lets us repair the online list
    // (join/leave lines can be missed if the console scrolls fast), which is what makes the
    // Players tab's Refresh actually show the true current players.
    private static final java.util.regex.Pattern LIST_PATTERN =
            java.util.regex.Pattern.compile("players online:\s*(.*)");

    /** Feeds one console line through the join/leave parser -- call this for every line read from the process, alongside whatever also displays it in the Console tab. */
    public void observeConsoleLine(String line) {
        if (line == null) return;
        var joined = JOINED_PATTERN.matcher(line);
        if (joined.find()) {
            onlinePlayers.add(joined.group(1));
            return;
        }
        var left = LEFT_PATTERN.matcher(line);
        if (left.find()) {
            onlinePlayers.remove(left.group(1));
            return;
        }
        var listed = LIST_PATTERN.matcher(line);
        if (listed.find()) {
            // A `list` reply is authoritative -- replace the whole set with what the server says.
            String raw = listed.group(1).trim();
            java.util.Set<String> fresh = new java.util.LinkedHashSet<>();
            if (!raw.isEmpty()) {
                for (String name : raw.split("\s*,\s*")) {
                    if (!name.isEmpty()) fresh.add(name);
                }
            }
            synchronized (onlinePlayers) {
                onlinePlayers.clear();
                onlinePlayers.addAll(fresh);
            }
        }
    }

    /** True if this console line looks like a vanilla `list` command reply header. */
    public static boolean isListReply(String line) {
        return line != null && line.contains("players online:");
    }

    /** Whether the last action was a `list` request waiting on its reply (so Refresh can send one). */
    public void sendListCommand() throws IOException {
        if (!isRunning()) throw new IllegalStateException("Server isn't running.");
        sendCommand("list");
    }

    public List<String> getOnlinePlayers() {
        synchronized (onlinePlayers) {
            return new ArrayList<>(onlinePlayers);
        }
    }

    public boolean isRunning() {
        return process != null && process.isAlive();
    }

    /**
     * Starts the server. jarOrNull is what ServerDownloader.ensureServerJar returned -- a real
     * jar for Vanilla/Purpur/Fabric, or null for modern Forge (which launches via generated
     * @args files instead of a single -jar target).
     */
    public Process start(ServerInstance server, Path serverDir, Path jarOrNull, String javaBinary) throws Exception {
        onlinePlayers.clear();
        acceptEula(serverDir);

        List<String> command = new ArrayList<>();
        command.add(javaBinary);
        command.add("-Xms" + server.ramMinMb + "M");
        command.add("-Xmx" + server.ramMaxMb + "M");

        if (jarOrNull != null) {
            command.add("-jar");
            command.add(jarOrNull.toString());
        } else {
            // Modern Forge/NeoForge: run.sh/run.bat wrap exactly this pattern -- an @user_jvm_args.txt
            // plus a per-OS @..._args.txt generated by the installer under libraries/. We build
            // the same command ourselves instead of shelling out to run.sh so RAM flags above
            // (which the user actually controls in this launcher) take effect consistently,
            // rather than whatever the installer's own script hardcoded.
            Path argsFile = findLoaderArgsFile(serverDir, server.type, server.minecraftVersion);
            if (argsFile == null) {
                String loaderName = server.type == ServerType.NEOFORGE ? "NeoForge" : "Forge";
                throw new IllegalStateException(loaderName + " server files look incomplete -- no launch "
                        + "args file for Minecraft " + server.minecraftVersion + " was found under "
                        + serverDir + "/libraries. Open Change Version (or recreate this server) to "
                        + "install a complete " + loaderName + " build.");
            }
            command.add("@" + serverDir.relativize(argsFile));
        }
        command.add("nogui");

        ProcessBuilder pb = new ProcessBuilder(command);
        pb.directory(serverDir.toFile());
        pb.redirectErrorStream(true);
        process = pb.start();
        stdin = process.getOutputStream();
        return process;
    }

    /** Graceful stop via the "stop" console command; falls back to killing the process if it doesn't exit in time. */
    public void stop() {
        if (!isRunning()) return;
        try {
            sendCommand("stop");
            boolean exited = process.waitFor(30, java.util.concurrent.TimeUnit.SECONDS);
            if (!exited) {
                process.destroyForcibly();
            }
        } catch (Exception e) {
            process.destroyForcibly();
        } finally {
            onlinePlayers.clear();
        }
    }

    public void sendCommand(String command) throws IOException {
        if (!isRunning() || stdin == null) throw new IllegalStateException("Server isn't running.");
        stdin.write((command + "\n").getBytes(java.nio.charset.StandardCharsets.UTF_8));
        stdin.flush();
    }

    /**
     * The launch-args file to use for {@code mcVersion}, for whichever of Forge / NeoForge this server
     * is.
     *
     * <p>Modern Forge generates one under
     * {@code libraries/net/minecraftforge/forge/<mcversion>-<forgeversion>/}; modern NeoForge under
     * {@code libraries/net/neoforged/neoforge/<neoforgeversion>/} (directory named after NEOFORGE's
     * own version, e.g. {@code 26.2.0.88}). Either way it is looked up BY VERSION first: this used to
     * be a plain directory walk returning the first {@code *_args.txt} it found, which silently picked
     * whichever build happened to come first in the walk -- the leftover args file of the OLD version
     * after a version change, so the server was launched with the wrong loader (one of the ways a
     * version change turned into a crash on the next start).
     *
     * <p>MC 1.20.1's NeoForge is the exception that proves the rule: it was published as Forge-style
     * {@code 1.20.1-47.1.x} and installed under Forge's own path, so that root is checked too.
     *
     * <p>A folder with only one installed build still resolves exactly as before: the version-matched
     * lookup finds it, and the unrestricted walk underneath is the fallback for layouts we don't
     * recognise (or for a folder where the version was never recorded).
     */
    private Path findLoaderArgsFile(Path serverDir, ServerType type, String mcVersion) {
        String suffix = platformArgsSuffix();
        Path forgeRoot = serverDir.resolve("libraries").resolve("net").resolve("minecraftforge").resolve("forge");
        String forgePrefix = (mcVersion == null || mcVersion.isBlank()) ? null : mcVersion + "-";

        if (type == ServerType.NEOFORGE) {
            Path neoRoot = serverDir.resolve("libraries").resolve("net").resolve("neoforged").resolve("neoforge");
            NeoForgeInstaller.Target target = NeoForgeInstaller.targetFor(mcVersion);
            String neoPrefix = target == null ? null : target.versionPrefix();
            Path args = argsFileInRoot(neoRoot, neoPrefix, suffix);
            if (args != null) return args;
            // Legacy 1.20.1 NeoForge installs Forge-style under Forge's own path.
            args = argsFileInRoot(forgeRoot, forgePrefix, suffix);
            if (args != null) return args;
        } else {
            Path args = argsFileInRoot(forgeRoot, forgePrefix, suffix);
            if (args != null) return args;
        }
        return findArgsFileUnder(serverDir.resolve("libraries"), suffix);
    }

    /**
     * The args file inside the version-matching build directory under {@code root}, or -- when there is
     * no usable version directory -- the first platform args file at or under {@code root}.
     *
     * @param prefix directory-name prefix that identifies the wanted build, or null/blank to skip
     *               version matching entirely (an unknown version: any args file beats none)
     */
    private Path argsFileInRoot(Path root, String prefix, String suffix) {
        if (Files.isDirectory(root) && prefix != null && !prefix.isBlank()) {
            try (Stream<Path> stream = Files.list(root)) {
                var matchingDirs = stream.filter(Files::isDirectory)
                        .filter(p -> p.getFileName().toString().startsWith(prefix))
                        .sorted(java.util.Comparator.comparing(p -> p.getFileName().toString()))
                        .toList();
                for (Path dir : matchingDirs) {
                    Path args = findArgsFileUnder(dir, suffix);
                    if (args != null) return args;
                }
            } catch (IOException ignored) {
                // Fall through to the unrestricted search below.
            }
        }
        return findArgsFileUnder(root, suffix);
    }

    /** Any platform args file at or under {@code root}, or null when there is none. */
    private Path findArgsFileUnder(Path root, String suffix) {
        if (!Files.isDirectory(root)) return null;
        try (Stream<Path> walk = Files.walk(root)) {
            return walk.filter(p -> p.getFileName().toString().endsWith(suffix))
                    .sorted()
                    .findFirst().orElse(null);
        } catch (IOException e) {
            return null;
        }
    }

    /** Per-OS args file name modern Forge generates, e.g. {@code unix_args.txt} / {@code win_args.txt}. */
    private static String platformArgsSuffix() {
        return System.getProperty("os.name").toLowerCase().contains("win") ? "win_args.txt" : "unix_args.txt";
    }

    private void acceptEula(Path serverDir) throws IOException {
        Path eula = serverDir.resolve("eula.txt");
        if (Files.exists(eula)) {
            String content = Files.readString(eula);
            if (content.contains("eula=true")) return;
        }
        // The person is choosing to run their own server through DeyLauncher's own server
        // manager -- that choice is the acceptance. Writing this file is what the vanilla
        // server itself requires before it will start at all; nothing here is a substitute
        // for actually agreeing to Mojang's EULA, which the person is doing by using this
        // feature in the first place.
        Files.writeString(eula, "eula=true\n");
    }
}
