package com.deylauncher.server;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

public class ServerProcessManager {

    private Process process;
    private OutputStream stdin;

    public boolean isRunning() {
        return process != null && process.isAlive();
    }

    /**
     * Starts the server. jarOrNull is what ServerDownloader.ensureServerJar returned -- a real
     * jar for Vanilla/Purpur/Fabric, or null for modern Forge (which launches via generated
     * @args files instead of a single -jar target).
     */
    public Process start(ServerInstance server, Path serverDir, Path jarOrNull, String javaBinary) throws Exception {
        acceptEula(serverDir);

        List<String> command = new ArrayList<>();
        command.add(javaBinary);
        command.add("-Xms" + server.ramMinMb + "M");
        command.add("-Xmx" + server.ramMaxMb + "M");

        if (jarOrNull != null) {
            command.add("-jar");
            command.add(jarOrNull.toString());
        } else {
            // Modern Forge: run.sh/run.bat wrap exactly this pattern -- an @user_jvm_args.txt
            // plus a per-OS @..._args.txt generated by the installer under libraries/. We build
            // the same command ourselves instead of shelling out to run.sh so RAM flags above
            // (which the user actually controls in this launcher) take effect consistently,
            // rather than whatever the installer's own script hardcoded.
            Path argsFile = findForgeArgsFile(serverDir);
            if (argsFile == null) {
                throw new IllegalStateException("Forge server files look incomplete -- no launch "
                        + "args file found under " + serverDir + "/libraries. Try recreating this server.");
            }
            command.add("@" + serverDir.relativize(argsFile));
        }
        command.add("nogui");

        ProcessBuilder pb = new ProcessBuilder(command);
        pb.directory(serverDir.toFile());
        pb.redirectErrorStream(true);
        process = pb.start();
        stdin = process.getOutputStream();
        return process;
    }

    /** Graceful stop via the "stop" console command; falls back to killing the process if it doesn't exit in time. */
    public void stop() {
        if (!isRunning()) return;
        try {
            sendCommand("stop");
            boolean exited = process.waitFor(30, java.util.concurrent.TimeUnit.SECONDS);
            if (!exited) {
                process.destroyForcibly();
            }
        } catch (Exception e) {
            process.destroyForcibly();
        }
    }

    public void sendCommand(String command) throws IOException {
        if (!isRunning() || stdin == null) throw new IllegalStateException("Server isn't running.");
        stdin.write((command + "\n").getBytes(java.nio.charset.StandardCharsets.UTF_8));
        stdin.flush();
    }

    private Path findForgeArgsFile(Path serverDir) {
        Path librariesDir = serverDir.resolve("libraries");
        if (!Files.isDirectory(librariesDir)) return null;
        String suffix = System.getProperty("os.name").toLowerCase().contains("win") ? "win_args.txt" : "unix_args.txt";
        try (Stream<Path> walk = Files.walk(librariesDir)) {
            return walk.filter(p -> p.getFileName().toString().endsWith(suffix)).findFirst().orElse(null);
        } catch (IOException e) {
            return null;
        }
    }

    private void acceptEula(Path serverDir) throws IOException {
        Path eula = serverDir.resolve("eula.txt");
        if (Files.exists(eula)) {
            String content = Files.readString(eula);
            if (content.contains("eula=true")) return;
        }
        // The person is choosing to run their own server through DeyLauncher's own server
        // manager -- that choice is the acceptance. Writing this file is what the vanilla
        // server itself requires before it will start at all; nothing here is a substitute
        // for actually agreeing to Mojang's EULA, which the person is doing by using this
        // feature in the first place.
        Files.writeString(eula, "eula=true\n");
    }
}
